apiVersion: v1
kind: Service
metadata:
  name: tts-cache
  labels:
    app: tts-cache
spec:
  selector:
    app: tts-cache
  ports:
    - name: http
      port: 80
      targetPort: http
  type: ClusterIP
